[package]
name    = "server-artifacts-updater"
version = "0.1.0"
edition = "2021"

[dependencies]
indicatif = "0.17.8"
reqwest    = { version = "0.12.5", features = ["blocking", "json"] }
serde      = { version = "1.0.204", features = ["derive"] }
serde_json = "1.0.120"
zip        = "2.1.5"